library(DESeq)
sampleTable <- data.frame(
sampleName = c("Col_0", "PRsec6_1"),
fileName = c("colcount", "sec6count"),
condition = c("wt", "mutant")
)
# read count data generated by HTSeq
cds <- newCountDataSetFromHTSeqCount(sampleTable, directory=".")
cds <- estimateSizeFactors( cds )
sizeFactors(cds)
#normolize data
head( counts( cds, normalized=TRUE ) )

cds <- estimateDispersions(cds, method="blind", sharingMode="fit-only")
res <- nbinomTest(cds, "wt", "mutant")
resSig <- res[ res$pval < 0.1, ]
resSig <- resSig[order(resSig$pval), ]
res$minus_log10padj <-	-(log10(res$padj))
res$log10baseMean <- log10(res$baseMean)
#write.csv(resSig, "PRsec6.sig.csv")
# begin ploting volcano
library(ggplot2)
none	<-	element_blank()
p<-ggplot(res,	aes(log2FoldChange,	minus_log10padj))	
p<-p+geom_point(fill="white",shape=1,size=2, na.rm=TRUE, aes(color=	log10baseMean))
p<-p+scale_colour_gradient(low = "#76EE00",	 high="#FF6347", breaks=c(0:5),	
na.value="grey50",guide="colourbar")
p<-p+theme(panel.background	 =	 none)	 +	 theme(panel.grid.major	 =	 none,	
panel.grid.minor=none)
p<-p+theme(panel.border=none)+theme(axis.line=element_line())
p<-p+theme()
p <- p+xlab("log2(PRsec6_1/Col_0)") + ylab(paste("-log10(Padj)"))
p <- p+ggtitle("PRsec6 vs Col_0 Volcano plot")
